language: android
android:
  components:
    - build-tools-19

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./emulator

script: mvn install -Pintegration-tests -Dandroid.device=test
